import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { Response } from 'express';

interface PdfPrescriptionData {
  code: string;
  status: string;
  notes?: string | null;
  createdAt: Date;
  consumedAt?: Date | null;
  patient: {
    user: { name: string; email: string };
    birthDate?: Date | null;
  };
  author: {
    specialty?: string | null;
    user: { name: string; email: string };
  };
  items: Array<{
    name: string;
    dosage?: string | null;
    quantity?: number | null;
    instructions?: string | null;
  }>;
}

@Injectable()
export class PrescriptionPdfService {
  async generatePdf(data: PdfPrescriptionData, res: Response): Promise<void> {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="prescription-${data.code}.pdf"`);

    doc.pipe(res);

    // Header
    doc
      .fillColor('#2563EB')
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('MedPrescribe', 50, 50);

    doc
      .fillColor('#64748B')
      .fontSize(10)
      .font('Helvetica')
      .text('Medical Prescription System', 50, 78);

    doc.moveTo(50, 95).lineTo(545, 95).strokeColor('#E2E8F0').lineWidth(1).stroke();

    // Prescription code & status
    doc
      .fillColor('#1E293B')
      .fontSize(16)
      .font('Helvetica-Bold')
      .text(`Prescription: ${data.code}`, 50, 110);

    const statusColor = data.status === 'consumed' ? '#16A34A' : '#D97706';
    doc
      .fillColor(statusColor)
      .fontSize(11)
      .font('Helvetica-Bold')
      .text(`Status: ${data.status.toUpperCase()}`, 50, 132);

    doc
      .fillColor('#64748B')
      .fontSize(10)
      .font('Helvetica')
      .text(`Issued: ${data.createdAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 50, 150);

    if (data.consumedAt) {
      doc.text(`Consumed: ${data.consumedAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 50, 165);
    }

    // Patient & Doctor info
    let y = 200;
    doc.moveTo(50, y - 10).lineTo(545, y - 10).strokeColor('#E2E8F0').stroke();

    doc
      .fillColor('#1E293B')
      .fontSize(13)
      .font('Helvetica-Bold')
      .text('Patient Information', 50, y);

    y += 20;
    doc
      .fillColor('#475569')
      .fontSize(11)
      .font('Helvetica')
      .text(`Name: ${data.patient.user.name}`, 50, y)
      .text(`Email: ${data.patient.user.email}`, 50, y + 16);

    if (data.patient.birthDate) {
      doc.text(
        `Date of Birth: ${new Date(data.patient.birthDate).toLocaleDateString()}`,
        50,
        y + 32,
      );
      y += 16;
    }

    y += 60;
    doc
      .fillColor('#1E293B')
      .fontSize(13)
      .font('Helvetica-Bold')
      .text('Prescribing Physician', 50, y);

    y += 20;
    doc
      .fillColor('#475569')
      .fontSize(11)
      .font('Helvetica')
      .text(`Name: ${data.author.user.name}`, 50, y)
      .text(`Email: ${data.author.user.email}`, 50, y + 16);

    if (data.author.specialty) {
      doc.text(`Specialty: ${data.author.specialty}`, 50, y + 32);
      y += 16;
    }

    y += 60;
    doc.moveTo(50, y - 10).lineTo(545, y - 10).strokeColor('#E2E8F0').stroke();

    // Medications
    doc
      .fillColor('#1E293B')
      .fontSize(13)
      .font('Helvetica-Bold')
      .text('Medications', 50, y);

    y += 25;

    for (const item of data.items) {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }

      doc
        .fillColor('#1E293B')
        .fontSize(11)
        .font('Helvetica-Bold')
        .text(`• ${item.name}`, 50, y);

      y += 18;

      if (item.dosage) {
        doc.fillColor('#475569').font('Helvetica').text(`  Dosage: ${item.dosage}`, 60, y);
        y += 16;
      }
      if (item.quantity) {
        doc.text(`  Quantity: ${item.quantity} units`, 60, y);
        y += 16;
      }
      if (item.instructions) {
        doc.text(`  Instructions: ${item.instructions}`, 60, y);
        y += 16;
      }
      y += 8;
    }

    // Notes
    if (data.notes) {
      y += 10;
      doc.moveTo(50, y).lineTo(545, y).strokeColor('#E2E8F0').stroke();
      y += 15;
      doc
        .fillColor('#1E293B')
        .fontSize(13)
        .font('Helvetica-Bold')
        .text('Clinical Notes', 50, y);
      y += 20;
      doc
        .fillColor('#475569')
        .fontSize(11)
        .font('Helvetica')
        .text(data.notes, 50, y, { width: 495 });
    }

    // Footer
    doc
      .fillColor('#94A3B8')
      .fontSize(9)
      .font('Helvetica')
      .text(
        `Generated by MedPrescribe on ${new Date().toISOString()}`,
        50,
        doc.page.height - 50,
        { align: 'center', width: 495 },
      );

    doc.end();
  }
}
